apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vote.name }}
  labels:
    app: {{ .Values.vote.group }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.vote.group }}
  template:
    metadata:
      labels:
        app: {{ .Values.vote.group}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.vote.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.vote.name }}
              containerPort: {{ .Values.vote.container_port }}